### ISSUE TITLE
Demo program fails

### ISSUE THREAD

**Issue by herohamp** [sholladay/pogo#3]
~/Documents/deno >>> deno ./server.ts --allow-net 0.0.0.0:8000
Compile file:///home/hampton/Documents/deno/server.ts
Download https://deno.land/x/pogo/main.js
Download https://deno.land/x/pogo/dependencies.js
Download https://deno.land/x/pogo/lib/respond.js
^[Download https://deno.land/x/pogo/lib/toolkit.js
Download https://deno.land/x/http@v0.8.0/http_status.ts
error: Uncaught Other: Import 'https://deno.land/x/http@v0.8.0/http_status.ts' failed: 404 Not Found
► js/errors.ts:33:12
    at DenoError (js/errors.ts:22:5)
    at maybeError (js/errors.ts:33:12)
    at maybeThrowError (js/errors.ts:39:15)
    at sendSync (js/dispatch.ts:137:5)
    at fetchModuleMetaData (js/compiler.ts:137:19)
    at _resolveModule (js/compiler.ts:254:12)
    at js/compiler.ts:370:37
    at resolveModuleNames (js/compiler.ts:368:24)
    at resolveModuleNamesWorker (third_party/node_modules/typescript/lib/typescript.js:89230:127)
    at resolveModuleNamesReusingOldState (third_party/node_modules/typescript/lib/typescript.js:89473:24)

**Comment by sholladay** [comment]
Yeah, I believe they got rid of the `http` alias on the Deno registry, so now it's a 404. The solution is to change the URL to access that module as a path within the `std` module. It's unfortunate that they didn't leave the existing URLs working. Pull request welcome!

// cc @ry

**Comment by sholladay** [comment]
Fixed by #4.
